# Generated by Django 5.0.4 on 2024-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='phone',
        ),
        migrations.AddField(
            model_name='operation',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
