# Generated by Django 5.0.4 on 2024-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_operation_address_remove_operation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='operation',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
